### ISSUE TITLE
"Database not found" error not showing.

### ISSUE THREAD

**Issue by Andromeda606** [om-mani-padme-hum/mysql-await#3]
if the database does not exist on the server, the con.on("error") method will never run. The awaitQuery part can only capture.
```JS
let con = await mysql.createConnection({
        host: "127.0.0.1",
        user: "root",
        password: "",
        database: database
    });
//not working bottom
con.on("error", (err, result) => {
        console.log(result);
        console.log(err);
    });
const sql = "CREATE DATABASE " + database;
    let result = await con.awaitQuery(sql);
    console.log(result); //ERROR! DATABASE NOT FOUND

```
it should return DATABASE NOT FOUND error in on("error") method

**Comment by om-mani-padme-hum** [comment]
Stale and couldn't make sense of issue.  Closing.  If still an issue, please re-open with full example and explanation of unexpected behavior.

**Comment by Andromeda606** [comment]
rewritten properly

**Comment by om-mani-padme-hum** [comment]
This issue appears to be related to this peculiarity of the callback version of the MySQL library:

<img width="738" alt="image" src="https://user-images.githubusercontent.com/26016332/181926099-5ce4ca1b-cd5a-4f5e-a122-3b2d65a3d6ec.png">

Therefore, since the user of mysql-await does not have control over whether or not to pass a callback function, a callback is always provided and an error is thrown if encountered.  Per the above, providing a callback disables the emitting of the error to the event listener.

I've therefore added a new config property called throwErrors which can be set to true or false.  I've also manually emitted errors in all callbacks.  So now, .on(`error`, (err) => ...) should always work; and errors will also be thrown unless the config has throwErrors set to false.

Thanks for the bug report!
